# External gems
# jekyll-sitemap
plugins:
  - jekyll-paginate

# Site settings
name: Oak Technical Services
version: 0.13.2
google_analytics_ua:

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/thoughts/:num/"
inter_post_navigation: true
permalinks: pretty
permalink: "thoughts/:title/"
include: ["pages", "thoughts"]
future: true
safe: false

# prod
url: "www.oakts.com"
#baseurl: "/thoughts"
# local dev
#url: "http://127.0.0.1:4000"
repos:

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/


# Build settings
markdown: kramdown
exclude:
- ".ruby-version"
- ".sass-cache"
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- config
- css
- img
- js
- manifest.yml
- node_modules
- package.json
- vendor
- circle.yml
- assets/src
